default:
  artifacts:
    expire_in: 1 week
  image:
    name: python:$PYTHON_VERSION

variables:
  PYTHON_VERSION: '3.12'  # switch to 3.12 once flake issues with 3.12.4 are resolved
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

.python_setup: &python_setup
  - python --version; pip --version
  - python -m pip install -U tox


.tested_python_versions:
  parallel:
    matrix:
      - PYTHON_VERSION: ['3.10', '3.13']

.supported_python_versions:
  parallel:
    matrix:
      - PYTHON_VERSION: ['3.10', '3.11', '3.12', '3.13']

.linux:
  image: python:$PYTHON_VERSION
  variables:
    OS_NAME: "linux"
  tags:
    - saas-linux-medium-amd64
  before_script:
    - *python_setup

stages:
  - lint
  - build
  - tests
#  - docs
#  - wheels
#  - deploy


###########################
######### LINT ############
###########################



lint:
  extends: .linux
  stage: lint
  needs: []
  script:
    - python -m tox -e lint

build:
  extends: .linux
  stage: build
  needs: []
  script:
    - python -m tox -e build

.tests:
  extends: .tested_python_versions
  script:
    - python -m tox -e tests
  stage: tests
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

tests:
  extends:
    - .linux
    - .tests
  needs: ["build"]

