#!/usr/bin/env python
#
# Copyright (c) 2026 Authors and contributors
# (see the AUTHORS.rst file for the full list of names)
#
# Released under the GNU Public Licence, v3 or any higher version
# SPDX-License-Identifier: GPL-3.0-or-later

"""Configuration file for the Sphinx documentation builder.

This file does only contain a selection of the most common options. For a full list see
the documentation: http://www.sphinx-doc.org/en/master/config
"""

import sys
from datetime import datetime
from importlib.metadata import metadata
from pathlib import Path

# -- Path setup --------------------------------------------------------------

ROOT = Path(__file__).resolve().parents[2]
# Make the in-tree package importable for autodoc when building locally
# without first installing solvate.
sys.path.insert(0, str(ROOT / "src"))

# -- Project information -----------------------------------------------------

project = "solvate"
project_dict = metadata(project)
author = project_dict["Author"]
version = project_dict["Version"]
copyright = f"{datetime.now().date().year}, {author}"

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings.
extensions = [
    "sphinx.builders.linkcheck",  # Check that external links are working
    "sphinx.ext.autodoc",  # import the modules you are documenting
    "sphinx.ext.viewcode",  # link to source files from docs
    "sphinx.ext.intersphinx",  # generate links to in external projects
    "sphinx.ext.mathjax",  # Render math via JavaScript
    "sphinx.ext.napoleon",  # Support for NumPy and Google style docstrings
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames. You can specify multiple suffix as a list of
# string: note: do not add .ipynb when nbspinx is enabled, otherwise you get the
# "missing title" error
source_suffix = [".rst"]

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns: list[str] = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "tango"

# -- Autodoc -----------------------------------------------------------------

autodoc_default_options = {
    "members": True,
    "show-inheritance": True,
}
autodoc_typehints = "none"

# -- Options for HTML output -------------------------------------------------

html_theme = "furo"
html_title = "solvate"
html_favicon = "../static/logo.ico"
html_static_path = ["../static"]
repository_url = next(
    (
        url
        for label, url in (
            i.split(", ") for i in project_dict.get_all("Project-URL") or []
        )
        if label == "repository"
    )
)

html_theme_options = {
    "navigation_with_keys": True,
    "footer_icons": [
        {
            "name": "GitHub",
            "url": repository_url,
            "html": "",
            "class": "fa-brands fa-github fa-2x",
        },
    ],
    "top_of_page_buttons": [],
    "light_logo": "logo_solvate.svg",
    "dark_logo": "logo_solvate.svg",
    "sidebar_hide_name": True,
}

# font-awesome logos
html_css_files = [
    "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/fontawesome.min.css",  # noqa: E501
    "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/solid.min.css",  # noqa: E501
    "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/brands.min.css",  # noqa: E501
]

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "solvatedoc"


# -- Options for LaTeX output ------------------------------------------------

latex_elements: dict[str, str] = {}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "solvate.tex",
        "solvate Documentation",
        "see the file AUTHORS for the full list of names",
        "manual",
    ),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "solvate", "solvate Documentation", [author], 1)]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "solvate",
        "solvate Documentation",
        author,
        "solvate",
        "Solvate confined geometries for MD simulations.",
        "Miscellaneous",
    ),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# A list of files that should not be packed into the epub file.
epub_exclude_files = ["search.html"]


# -- Extension configuration -------------------------------------------------

# Configuration for intersphinx: refer to the Python standard library
# and other packages used by solvate.
intersphinx_mapping = {
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
    "matplotlib": ("https://matplotlib.org/stable/", None),
    "MDAnalysis": ("https://docs.mdanalysis.org/stable/", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "python": ("https://docs.python.org/3/", None),
}
