name: Tests

on:
  push:
    branches: [main]
  pull_request:
    # Check all PR
  schedule:
    # check once a week on mondays
    - cron: '0 10 * * 1'

jobs:
  tests:
    runs-on: ubuntu-latest
    variables:
      PYTHON_VERSION: 3.13

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python ${PYTHON_VERSION}
      uses: actions/setup-python@v5
      with:
        python-version: ${PYTHON_VERSION}
        check-latest: true

    - run: python -m pip install tox coverage[toml]

    - name: run Python tests
      run: |
        tox -e tests
        # coverage xml

    # - name: upload to codecov.io
    #   uses: codecov/codecov-action@v5
    #   with:
    #     fail_ci_if_error: true
    #     files: tests/coverage.xml
    #     token: ${{ secrets.CODECOV_TOKEN }}
